'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Research_Pub

    '''<summary>
    '''updDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDashboard As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSelectedYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedYear As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yearDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yearDropdown As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sumType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumType1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sumType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumType2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkAllColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllColumns As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkYear As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMonth As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkType As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTitle As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAuthors As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSource As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVolume As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIssue As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPages As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkDOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDOI As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkInterCollab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInterCollab As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkAcademicCollab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAcademicCollab As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkSDG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSDG As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkCluster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCluster As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkQ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQ1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkQ2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQ2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkQ3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQ3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkQ4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkQ4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTop1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTop1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTop10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTop10 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTCI1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTCI1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTCI2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTCI2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkTCI3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTCI3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''btnLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoad As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnType1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnType2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data As Global.System.Web.UI.WebControls.GridView
End Class
