'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class testRES

    '''<summary>
    '''updDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDashboard As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblSelectedYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedYear As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''yearDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yearDropdown As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sumType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumType1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sumType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sumType2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''card11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents card11 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''card12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents card12 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''card13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents card13 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''card19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents card19 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbl19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkAllColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllColumns As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTitle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAuthors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAuthors As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSource As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVolume As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIssue As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPages As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDOI As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''phKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phKPI As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''btnApply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApply As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnType1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnType2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data As Global.System.Web.UI.WebControls.GridView
End Class
